shell = require 'shelljs'

task 'compile-coffee', ->
  console.log 'Compiling coffee files.'
  shell.exec 'coffee -c -o lib src'
  
task 'build', ->
  shell.rm '-rf', 'lib'
  shell.mkdir 'lib'
  invoke 'compile-coffee'
  shell.cp 'src/child.coffee', 'lib'
  