// Generated by CoffeeScript 1.3.3
(function() {
  var dashboard;

  console.log(process.argv);

  dashboard = require('./base').createDashboard(require(process.argv[2]));

  dashboard.on('ready', function() {
    return process.send({
      event: 'ready'
    });
  });

  dashboard.on('output', function(data) {
    return process.send({
      event: 'output',
      data: data
    });
  });

  dashboard.on('executing', function() {
    return process.send({
      event: 'executing'
    });
  });

  process.on('message', function(msg) {
    switch (msg.event) {
      case 'input':
        return dashboard.input(msg.data);
      case 'start':
        return dashboard.start();
      case 'interrupt':
        return dashboard.interrupt();
      case 'exit':
        return process.exit();
    }
  });

  process.on('SIGINT', function() {
    return dashboard.interrupt();
  });

}).call(this);
