shell = require 'shelljs'

task 'compile-coffee', ->
  console.log 'Compiling coffee files.'
  shell.exec 'coffee -c -o lib src'

task 'test', ->
  shell.exec 'coffee -c test/test.coffee'
  shell.exec 'mocha -u bdd -t 10000 test/test' 
  shell.rm './test/test.js'  

task 'build', ->
  shell.rm '-rf', 'lib'
  shell.mkdir 'lib'
  invoke 'compile-coffee'
  shell.cp 'src/child.coffee', 'lib'
  