// Generated by CoffeeScript 1.3.3
(function() {
  var coffee, util, _,
    _this = this;

  coffee = require('coffee-script');

  util = require('util');

  _ = require('underscore');

  process.on('message', function(code) {
    var result, split;
    try {
      result = coffee["eval"]("(" + code + "\n)", {
        filename: 'dashboard',
        modulename: 'dashboard'
      });
      split = code.trim().split(/\s+/);
      if (result && _.isFunction(result.toHtml)) {
        return process.send({
          type: 'html',
          value: result.toHtml()
        });
      } else if (result && _.isFunction(result.toWidget)) {
        return process.send({
          type: 'widget',
          value: result.toWidget()
        });
      } else {
        return process.send({
          type: 'result',
          value: util.inspect(result)
        });
      }
    } catch (err) {
      return process.send({
        type: 'error',
        value: err.stack.toString()
      });
    }
  });

}).call(this);
